baseurl = "https://www.kimberleyelcess.com/"
languageCode = "en-us"
title = "Kimberley's website"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/Elcess"
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/kimberleyelcess/"

[params]
    description = "A website for Elcess' data science explorations."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "HomeImage.jpg"
    width = 50
    height = 50
    alt = "Logo"

